# Generated by Django 4.2.7 on 2023-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('appearance', models.TextField(max_length=250)),
                ('seen', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
    ]
